name: Build FreeRDP against Python libraries
on: [push]

jobs:
  freerdp:
    name: Build FreeRDP
    env:
      PYTHON: "3.13"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - id: cache-downloads-restore
        uses: actions/cache/restore@v4
        with:
          path: dl
          key: download-freerdp-9

      - name: download
        shell: sh
        run: |
          ./python.sh -m builder download_freerdp

      - uses: actions/cache/save@v4
        with:
          path: dl
          key: ${{ steps.cache-downloads-restore.outputs.cache-primary-key }}

      - name: Build fake deps
        shell: sh
        run: |
          ./python.sh -m builder fake_compile_openssl
          ./python.sh -m builder fake_compile_zlib

      - name: Build FreeRDP
        shell: sh
        run: |
          ./python.sh -m builder build_freerdp

      - name: Assemble outputs
        shell: sh
        run: |
          ./python.sh -m builder assemble_freerdp

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: freerdp
          path: freerdp-final
