name: Build FreeRDP against Python libraries
on: [push]

jobs:
  freerdp:
    name: Build FreeRDP
    env:
      PYTHON: "C:/hostedtoolcache/windows/Python/3.13.3/x64/python.exe"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - id: cache-downloads-restore
        uses: actions/cache/restore@v4
        with:
          path: dl
          key: download-freerdp-8

      - name: download
        shell: sh
        run: |
          ./python.sh builder.py download_freerdp

      - uses: actions/cache/save@v4
        with:
          path: dl
          key: ${{ steps.cache-downloads-restore.outputs.cache-primary-key }}

      - name: Build fake deps
        shell: sh
        run: |
          ./python.sh builder.py fake_compile_openssl
          ./python.sh builder.py fake_compile_zlib

      - name: Build FreeRDP
        shell: sh
        run: |
          ./python.sh builder.py build_freerdp

      - name: Assemble outputs
        shell: sh
        run: |
          ./python.sh builder.py assemble_freerdp

      - name: Upload FreeRDP build
        uses: actions/upload-artifact@v4
        with:
          name: freerdp
          path: freerdp-final
