name: Build stoken_bfasst against Python libraries
on: [push]

jobs:
  stoken_bfasst:
    name: Build stoken_bfasst
    env:
      PYTHON: "C:/hostedtoolcache/windows/Python/3.13.3/x64/python.exe"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - id: cache-downloads-restore
        uses: actions/cache/restore@v4
        with:
          path: dl
          key: download-stoken_bfasst-3

      - name: download
        shell: sh
        run: |
          ./python.sh -m builder download_stoken_bfasst

      - uses: actions/cache/save@v4
        with:
          path: dl
          key: ${{ steps.cache-downloads-restore.outputs.cache-primary-key }}

      - name: Build fake deps
        shell: sh
        run: |
          ./python.sh -m builder fake_compile_openssl

      - name: Build stoken_bfasst
        shell: sh
        run: |
          # FIXME: pin setuptools by hash
          ./python.sh -m builder install_setuptools
          ./python.sh -m builder build_stoken_bfasst

      - name: Assemble outputs
        shell: sh
        run: |
          ./python.sh -m builder assemble_stoken_bfasst

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: stoken_bfasst
          path: stoken_bfasst-final
